[GU-API] HUB info
golemfactory/golem-unlimited pull request #194
Opened 2019-04-04 14:05 UTC by prekucki

2019-04-04 21:05 UTC, quilir requested changes

2019-04-04 21:05 UTC, quilir commented on gu-hub-api.yaml
> +        description: hub protocool capabilities
```suggestion
        description: hub protocol capabilities
```

2019-04-04 21:05 UTC, quilir commented on gu-hub-api.yaml
> +        description: node public key hash in etherium format
```suggestion
        description: node public key hash in ethereum format
```

2019-04-04 21:05 UTC, quilir commented on gu-hub/src/local_service.rs
> +struct ServiceRunner {}
Never used struct

2019-04-04 21:05 UTC, quilir commented on gu-hub/webapp/directives/guListProvider.js
> +            console.log('ddd');
Left debug log

2019-04-04 21:05 UTC, quilir commented on gu-plugin-api/src/lib.rs
> +        .and_then(|v: serde_json::Value| Ok(log::info!("registed service [{}]", v.to_string())))
```suggestion
        .and_then(|v: serde_json::Value| Ok(log::info!("registered service [{}]", v.to_string())))
```

2019-04-04 21:05 UTC, quilir commented on gu-plugin-api/src/lib.rs
> +pub fn register_server(url: &str, cmd_name: &str) -> impl Future<Item = (), Error = ()> {
```suggestion
pub fn register_service(url: &str, cmd_name: &str) -> impl Future<Item = (), Error = ()> {
```

2019-04-08 11:25 UTC, prekucki commented on gu-hub/src/local_service.rs
> +struct ServiceRunner {}
I know. Implementation pending. Service runner should activate local services relevant to active plugins.

2019-04-08 14:49 UTC, merged